sudo: required

services:
  - docker

before_install:
  - docker build -t mo-docker-react -f Dockerfile.dev .

script:
  - docker run mo-docker-react npm run test -- --coverage

  - travis_wait 20 julia --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)';